services:
  postgres:
    image: postgres:18
    container_name: books-db
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  redis:
    image: redis:7
    container_name: books-redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
